name: Prepare VM for build
description: Install required packages
runs:
  using: "composite"
  steps:
    - name: mount ccache shared folder
      shell: bash
      run: |
        sudo mkdir /mnt/ccache
        sudo chmod 777 /mnt/ccache
        sudo mount -t virtiofs ccache /mnt/ccache/
