name: Build and test

on:
  workflow_call:
    inputs:
      build_target:
        type: string
        default: "cloud/blockstore/apps/"
        description: "limit build and test to specific target"
      test_target:
        type: string
        default: "cloud/blockstore/"
        description: "limit build and test to specific target"
      build_preset:
        type: string
      runner_kind:
        type: string
        required: true
        description: "self-hosted or provisioned"
      runner_label:
        type: string
        default: "linux"
        description: "runner label"
      run_build:
        type: boolean
        default: true
        description: "run build"
      run_tests:
        type: boolean
        default: true
        description: "run tests"
      test_threads:
        type: string
        default: '28'
        description: "Test threads count"
      link_threads:
        type: string
        default: '8'
        description: "link threads count"
      test_size:
        type: string
        default: "small,medium,large"
      test_type:
        type: string
        default: "unittest,py3test,py2test,pytest"
      folder_prefix:
        type: string
        default: "ya-"
      update_bazel_cache:
        type: boolean
        default: false
        description: "Update remote cache"
      cache_tests:
        type: boolean
        default: false
        description: "Use cache for tests"

jobs:
  build-and-test:
    name: Build and test ${{ inputs.build_preset }}
    runs-on: [ self-hosted, "${{ inputs.runner_kind }}", "${{ inputs.runner_label }}" ]
    steps:
    - name: Checkout PR
      uses: actions/checkout@v3
      if: github.event.pull_request.head.sha != ''
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Checkout
      uses: actions/checkout@v3
      if: github.event.pull_request.head.sha == ''

    - name: Build
      uses: ./.github/actions/build
      if: inputs.run_build
      with:
        build_target: ${{ inputs.build_target }}
        build_preset: ${{ inputs.build_preset }}
        update_bazel_cache: ${{ inputs.update_bazel_cache }}
        bazel_remote_uri: ${{ vars.REMOTE_CACHE_URL_YA || '' }}
        bazel_remote_username: ${{ secrets.REMOTE_CACHE_USERNAME }}
        bazel_remote_password: ${{ secrets.REMOTE_CACHE_PASSWORD }}
        link_threads: ${{ inputs.link_threads }}

    - name: Run tests
      uses: ./.github/actions/test
      if: inputs.run_tests
      with:
        test_target: ${{ inputs.test_target }}
        build_preset: ${{ inputs.build_preset }}
        test_size: ${{ inputs.test_size }}
        test_type: ${{ inputs.test_type }}
        bazel_remote_uri: ${{ vars.REMOTE_CACHE_URL_YA || '' }}
        link_threads: ${{ inputs.link_threads }}
        test_threads: ${{ inputs.test_threads }}
