name: Nightly build
run-name: |
  ${{ github.event_name == 'workflow_dispatch'
      && format(
          'Nightly build (manual) clean_ya_dir:{0} build_target:{1} test_target:{2}',
          inputs.clean_ya_dir, inputs.build_target, inputs.test_target
        )
      || format('Nightly build (schedule) schedule:"{0}"', github.event.schedule)
    }}
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
    inputs:
      clean_ya_dir:
        description: 'Clean ya dir'
        type: boolean
        required: false
        default: true
      build_target:
        description: 'Build target'
        type: string
        required: false
        #default: 'cloud/tasks/'
        default: 'cloud/blockstore/apps/,cloud/filestore/apps/,cloud/disk_manager/,cloud/tasks/'
      test_target:
        description: 'Test target'
        type: string
        required: false
        #default: 'cloud/tasks/'
        default: 'cloud/blockstore/,cloud/filestore/,cloud/disk_manager/,cloud/tasks/'


jobs:
  build:
    name: Build/test x86_64 using YA (relwithdebinfo)
    uses: ./.github/workflows/build_and_test_on_demand.yaml
    secrets: inherit
    with:
      build_target: ${{ inputs.build_target || 'cloud/blockstore/apps/,cloud/filestore/apps/,cloud/disk_manager/,cloud/tasks/' }}
      test_target: ${{ inputs.test_target || 'cloud/blockstore/,cloud/filestore/,cloud/disk_manager/,cloud/tasks/' }}
      build_preset: relwithdebinfo
      cache_update_build: true
      cache_update_tests: false
      sleep_after_tests: 1
      test_threads: 6
      upload_ya_dir: true
      clean_ya_dir: ${{ inputs.clean_ya_dir || true }}
