name: Orchestrator test
run-name: ${{ format('Orchestrator test ({0} {1} {2})', github.event_name, github.event.schedule == '*/2 * * * *' && 'light' || (inputs.run_light == 'yes' && 'light' || 'none'), github.event.schedule == '*/3 * * * *' && 'heavy' || (inputs.run_heavy == 'yes' && 'heavy' || 'none'))  }}
      
on:
  schedule:
    - cron: '*/2 * * * *' # Every 30 minutes for light VMs
    - cron: '*/3 * * * *' # Every 15 minutes for heavy VMs  
  workflow_dispatch:
    inputs:
      provision_mode:
        description: 'Provision mode (if set to initial it will use ubuntu-latest image)'
        type: choice
        options:
          - initial
          - regular
        required: true
        default: 'regular'
      loop:
        description: 'Loop the action'
        type: choice
        options:
          - "yes"
          - "no"
        required: false
        default: "no"
      run_light:
        description: 'Run light VMs'
        type: choice
        options:
          - "yes"
          - "no"
        required: false
        default: "yes"
      run_heavy:
        description: 'Run heavy VMs'
        type: choice
        options:
          - "yes"
          - "no"
        required: false
        default: "yes"

concurrency:
  group: orchestrator-${{ github.event.schedule == '*/2 * * * *' && 'light' || (inputs.run_light == 'yes' && 'light' || 'none')}}-${{ github.event.schedule == '*/3 * * * *' && 'heavy' || (inputs.run_heavy == 'yes' && 'heavy' || 'none') }}
  cancel-in-progress: true

jobs:
  test:
    name: Orchestrator Test
    runs-on: [self-hosted, "self-hosted", "runner_light"]
    steps:
      - name: test
        run: echo "This is a test job for the orchestrator workflow."
